# Question

Will the code work? Why or why not?

```js
const getUsers = async () => {
  const url = "https://jsonplaceholder.typicode.com/users";
  const users = await fetch(url)
    .then((r) => r.json())
    .catch((err) => []);
  console.log(users);
  return users;
};
getUsers();
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer

yes, the code works becuase you are waiting for it to fetch url, then make that data into a JSON and finally, if there are any errors you want to catch them. While this code does work you should use `try/catch` becuase it works better with `async/await`.

# Teacher Feedback
